export type EmojiCategory = {
  id: string
  name: string
  icon: string
  emojis: { emoji: string; keywords: string[] }[]
}

export const EMOJI_CATALOG: EmojiCategory[] = [
  {
    id: "smileys",
    name: "Smileys",
    icon: "😀",
    emojis: [
      { emoji: "😀", keywords: ["grinning", "happy", "smile", "face"] },
      { emoji: "😃", keywords: ["smiley", "happy", "joy"] },
      { emoji: "😄", keywords: ["smile", "laugh", "happy"] },
      { emoji: "😁", keywords: ["grin", "beaming", "happy"] },
      { emoji: "😆", keywords: ["laughing", "satisfied", "lol"] },
      { emoji: "😅", keywords: ["sweat", "smile", "relief"] },
      { emoji: "🤣", keywords: ["rofl", "lol", "laughing", "floor"] },
      { emoji: "😂", keywords: ["joy", "tears", "laughing", "cry"] },
      { emoji: "🙂", keywords: ["slightly", "smiling", "okay"] },
      { emoji: "🙃", keywords: ["upside", "down", "silly", "irony"] },
      { emoji: "😉", keywords: ["wink", "flirt", "playful"] },
      { emoji: "😊", keywords: ["blush", "warm", "happy"] },
      { emoji: "😇", keywords: ["angel", "halo", "innocent"] },
      { emoji: "🥰", keywords: ["love", "hearts", "adore"] },
      { emoji: "😍", keywords: ["heart", "eyes", "love", "crush"] },
      { emoji: "🤩", keywords: ["star", "struck", "excited", "wow"] },
      { emoji: "😘", keywords: ["kiss", "love", "blow"] },
      { emoji: "😗", keywords: ["kissing", "face"] },
      { emoji: "😚", keywords: ["kiss", "closed", "eyes"] },
      { emoji: "😋", keywords: ["yum", "delicious", "tasty", "silly"] },
      { emoji: "😛", keywords: ["tongue", "playful"] },
      { emoji: "😜", keywords: ["wink", "tongue", "crazy"] },
      { emoji: "🤪", keywords: ["zany", "wild", "goofy"] },
      { emoji: "😝", keywords: ["squint", "tongue"] },
      { emoji: "🤗", keywords: ["hug", "open", "arms", "friendly"] },
      { emoji: "🤭", keywords: ["giggle", "oops", "hand", "mouth"] },
      { emoji: "🤫", keywords: ["shh", "quiet", "secret", "silence"] },
      { emoji: "🤔", keywords: ["thinking", "hmm", "ponder", "wonder"] },
      { emoji: "🤐", keywords: ["zipper", "silent", "quiet"] },
      { emoji: "🤨", keywords: ["eyebrow", "skeptical", "suspicious"] },
      { emoji: "😐", keywords: ["neutral", "meh", "blank"] },
      { emoji: "😑", keywords: ["expressionless", "unamused"] },
      { emoji: "😶", keywords: ["no", "mouth", "speechless"] },
      { emoji: "😏", keywords: ["smirk", "suggestive", "clever"] },
      { emoji: "😒", keywords: ["unamused", "annoyed"] },
      { emoji: "🙄", keywords: ["eyes", "rolling", "whatever"] },
      { emoji: "😬", keywords: ["grimace", "awkward", "yikes"] },
      { emoji: "🤥", keywords: ["lying", "pinocchio", "nose"] },
      { emoji: "😌", keywords: ["relieved", "calm", "peace"] },
      { emoji: "😔", keywords: ["pensive", "sad", "down"] },
      { emoji: "😪", keywords: ["sleepy", "tired", "tear"] },
      { emoji: "🤤", keywords: ["drooling", "delicious"] },
      { emoji: "😴", keywords: ["sleeping", "zzz", "tired"] },
      { emoji: "😷", keywords: ["mask", "sick", "health"] },
      { emoji: "🤒", keywords: ["thermometer", "fever", "ill"] },
      { emoji: "🤕", keywords: ["bandage", "hurt", "head"] },
      { emoji: "🤢", keywords: ["nauseated", "gross"] },
      { emoji: "🤮", keywords: ["vomiting", "sick", "puke"] },
      { emoji: "🤧", keywords: ["sneezing", "cold", "tissue"] },
      { emoji: "🥵", keywords: ["hot", "sweating", "summer"] },
      { emoji: "🥶", keywords: ["cold", "freezing", "ice"] },
      { emoji: "🥴", keywords: ["woozy", "dizzy", "tipsy"] },
      { emoji: "😵", keywords: ["dizzy", "knockout"] },
      { emoji: "🤯", keywords: ["mind", "blown", "exploding", "shock"] },
      { emoji: "🤠", keywords: ["cowboy", "hat"] },
      { emoji: "🥳", keywords: ["party", "celebration", "birthday"] },
      { emoji: "😎", keywords: ["cool", "sunglasses", "awesome"] },
      { emoji: "🤓", keywords: ["nerd", "glasses", "geek", "smart"] },
      { emoji: "🧐", keywords: ["monocle", "curious", "inspect"] },
      { emoji: "😕", keywords: ["confused", "puzzled"] },
      { emoji: "😟", keywords: ["worried", "nervous"] },
      { emoji: "🙁", keywords: ["frown", "sad"] },
      { emoji: "😮", keywords: ["surprised", "gasp", "open", "mouth"] },
      { emoji: "😯", keywords: ["hushed", "surprised"] },
      { emoji: "😲", keywords: ["astonished", "shocked"] },
      { emoji: "😳", keywords: ["flushed", "embarrassed", "wide", "eyes"] },
      { emoji: "🥺", keywords: ["pleading", "begging", "puppy", "eyes"] },
      { emoji: "😦", keywords: ["frowning", "open", "mouth"] },
      { emoji: "😧", keywords: ["anguished", "distressed"] },
      { emoji: "😨", keywords: ["fearful", "scared"] },
      { emoji: "😰", keywords: ["anxious", "blue", "sweat"] },
      { emoji: "😥", keywords: ["sad", "relieved", "phew"] },
      { emoji: "😢", keywords: ["crying", "tear", "sad"] },
      { emoji: "😭", keywords: ["sobbing", "bawling", "sad"] },
      { emoji: "😱", keywords: ["scream", "scared", "shocked"] },
      { emoji: "😖", keywords: ["confounded", "quivering"] },
      { emoji: "😣", keywords: ["persevering", "struggling"] },
      { emoji: "😞", keywords: ["disappointed", "sad"] },
      { emoji: "😓", keywords: ["downcast", "sweat"] },
      { emoji: "😩", keywords: ["weary", "exhausted", "tired"] },
      { emoji: "😫", keywords: ["tired", "frustrated"] },
      { emoji: "🥱", keywords: ["yawning", "bored", "sleepy"] },
      { emoji: "😤", keywords: ["triumph", "steam", "proud"] },
      { emoji: "😡", keywords: ["pouting", "angry", "mad"] },
      { emoji: "😠", keywords: ["angry", "grumpy"] },
      { emoji: "🤬", keywords: ["cursing", "swearing", "furious"] },
      { emoji: "💀", keywords: ["skull", "dead", "skeleton", "dying"] },
      { emoji: "💩", keywords: ["poop", "poo"] },
      { emoji: "🤡", keywords: ["clown", "circus"] },
      { emoji: "👻", keywords: ["ghost", "spooky", "halloween"] },
    ],
  },
  {
    id: "people",
    name: "People",
    icon: "👋",
    emojis: [
      { emoji: "👍", keywords: ["thumbs", "up", "like", "approve", "yes", "good"] },
      { emoji: "👎", keywords: ["thumbs", "down", "dislike", "no", "bad"] },
      { emoji: "👏", keywords: ["applause", "clapping", "bravo"] },
      { emoji: "🙌", keywords: ["hooray", "hands", "celebration", "praise"] },
      { emoji: "👐", keywords: ["open", "hands"] },
      { emoji: "🤲", keywords: ["palms", "up", "together"] },
      { emoji: "🤝", keywords: ["handshake", "agreement", "deal", "meeting"] },
      { emoji: "🤜", keywords: ["right", "fist", "bump"] },
      { emoji: "🤛", keywords: ["left", "fist", "bump"] },
      { emoji: "✊", keywords: ["fist", "power", "solidarity"] },
      { emoji: "👊", keywords: ["punch", "fist", "bump"] },
      { emoji: "✌️", keywords: ["peace", "victory", "two"] },
      { emoji: "🤞", keywords: ["fingers", "crossed", "luck", "hope"] },
      { emoji: "🤟", keywords: ["love", "you", "sign"] },
      { emoji: "🤘", keywords: ["rock", "on", "horns"] },
      { emoji: "👌", keywords: ["ok", "perfect", "okay"] },
      { emoji: "🤌", keywords: ["pinched", "fingers", "italian"] },
      { emoji: "🤏", keywords: ["pinching", "hand", "little", "bit"] },
      { emoji: "👈", keywords: ["point", "left"] },
      { emoji: "👉", keywords: ["point", "right"] },
      { emoji: "👆", keywords: ["point", "up"] },
      { emoji: "👇", keywords: ["point", "down"] },
      { emoji: "☝️", keywords: ["index", "up", "attention"] },
      { emoji: "✋", keywords: ["raised", "hand", "stop", "highfive"] },
      { emoji: "🤚", keywords: ["raised", "back", "of", "hand"] },
      { emoji: "🖐️", keywords: ["fingers", "splayed"] },
      { emoji: "🖖", keywords: ["vulcan", "salute", "spock"] },
      { emoji: "👋", keywords: ["wave", "hello", "goodbye", "hi"] },
      { emoji: "🤙", keywords: ["call", "me", "shaka"] },
      { emoji: "💪", keywords: ["flex", "muscle", "strong", "power"] },
      { emoji: "✍️", keywords: ["writing", "hand", "pen", "note"] },
      { emoji: "🙏", keywords: ["pray", "please", "thank", "you", "namaste"] },
      { emoji: "🧑‍🏫", keywords: ["teacher", "educator", "professor", "instructor"] },
      { emoji: "👩‍🏫", keywords: ["woman", "teacher", "educator", "instructor"] },
      { emoji: "👨‍🏫", keywords: ["man", "teacher", "educator", "instructor"] },
      { emoji: "🧑‍🎓", keywords: ["student", "graduate", "academic"] },
      { emoji: "👩‍🎓", keywords: ["woman", "student", "graduate"] },
      { emoji: "👨‍🎓", keywords: ["man", "student", "graduate"] },
      { emoji: "🧑‍💻", keywords: ["technologist", "developer", "coder", "programmer"] },
      { emoji: "👩‍💻", keywords: ["woman", "developer", "coder"] },
      { emoji: "👨‍💻", keywords: ["man", "developer", "coder"] },
      { emoji: "🧑‍🔬", keywords: ["scientist", "researcher", "chemist", "biologist"] },
      { emoji: "👩‍🔬", keywords: ["woman", "scientist", "researcher"] },
      { emoji: "👨‍🔬", keywords: ["man", "scientist", "researcher"] },
      { emoji: "🙋", keywords: ["raising", "hand", "question"] },
      { emoji: "🙋‍♂️", keywords: ["man", "raising", "hand"] },
      { emoji: "🙋‍♀️", keywords: ["woman", "raising", "hand"] },
      { emoji: "🙇", keywords: ["bowing", "respect"] },
      { emoji: "🙇‍♂️", keywords: ["man", "bowing"] },
      { emoji: "🙇‍♀️", keywords: ["woman", "bowing"] },
    ],
  },
  {
    id: "academic",
    name: "Academic",
    icon: "📚",
    emojis: [
      { emoji: "📚", keywords: ["books", "library", "study", "reading", "education"] },
      { emoji: "📖", keywords: ["open", "book", "read", "story"] },
      { emoji: "📕", keywords: ["red", "book"] },
      { emoji: "📗", keywords: ["green", "book"] },
      { emoji: "📘", keywords: ["blue", "book"] },
      { emoji: "📙", keywords: ["orange", "book"] },
      { emoji: "📓", keywords: ["notebook", "journal"] },
      { emoji: "📒", keywords: ["ledger", "yellow", "notebook"] },
      { emoji: "📑", keywords: ["bookmark", "tabs"] },
      { emoji: "🎓", keywords: ["graduation", "cap", "diploma", "degree", "university"] },
      { emoji: "🏫", keywords: ["school", "building", "classroom"] },
      { emoji: "🏛️", keywords: ["institution", "university", "classical", "hall"] },
      { emoji: "💡", keywords: ["idea", "lightbulb", "bright", "smart", "solution"] },
      { emoji: "📝", keywords: ["memo", "note", "pencil", "write", "assignment"] },
      { emoji: "✏️", keywords: ["pencil", "lead", "sketch"] },
      { emoji: "📐", keywords: ["triangular", "ruler", "geometry", "math"] },
      { emoji: "📏", keywords: ["straight", "ruler", "measure", "metric"] },
      { emoji: "🧪", keywords: ["test", "tube", "chemistry", "experiment", "science"] },
      { emoji: "🔬", keywords: ["microscope", "biology", "science", "research"] },
      { emoji: "🧬", keywords: ["dna", "genetics", "biology", "science"] },
      { emoji: "🔭", keywords: ["telescope", "astronomy", "physics", "stars"] },
      { emoji: "💻", keywords: ["laptop", "computer", "pc", "tech"] },
      { emoji: "🖥️", keywords: ["desktop", "computer", "monitor"] },
      { emoji: "⌨️", keywords: ["keyboard", "type"] },
      { emoji: "🖱️", keywords: ["mouse", "click"] },
      { emoji: "📊", keywords: ["bar", "chart", "graph", "analytics", "data"] },
      { emoji: "📈", keywords: ["chart", "increasing", "growth", "trends"] },
      { emoji: "📉", keywords: ["chart", "decreasing", "loss"] },
      { emoji: "🗂️", keywords: ["card", "index", "dividers", "curriculum"] },
      { emoji: "📁", keywords: ["file", "folder", "documents"] },
      { emoji: "📂", keywords: ["open", "file", "folder"] },
      { emoji: "📋", keywords: ["clipboard", "checklist", "syllabus"] },
      { emoji: "📌", keywords: ["pushpin", "pin", "pinned"] },
      { emoji: "📍", keywords: ["round", "pin", "location", "mark"] },
      { emoji: "📎", keywords: ["paperclip", "attachment"] },
      { emoji: "🖇️", keywords: ["linked", "paperclips"] },
      { emoji: "🔍", keywords: ["search", "magnifier", "left"] },
      { emoji: "🔎", keywords: ["search", "magnifier", "right"] },
      { emoji: "🔒", keywords: ["locked", "security", "private"] },
      { emoji: "✉️", keywords: ["envelope", "email", "mail"] },
      { emoji: "📩", keywords: ["envelope", "arrow", "received"] },
      { emoji: "📤", keywords: ["outbox", "tray", "sent"] },
      { emoji: "📥", keywords: ["inbox", "tray", "receive"] },
      { emoji: "📦", keywords: ["package", "parcel", "delivery"] },
      { emoji: "🏷️", keywords: ["label", "tag"] },
      { emoji: "📰", keywords: ["newspaper", "journal", "article"] },
      { emoji: "🗞️", keywords: ["rolled", "newspaper"] },
      { emoji: "📆", keywords: ["calendar", "date", "tearoff"] },
      { emoji: "📅", keywords: ["calendar", "schedule", "planner"] },
      { emoji: "🕒", keywords: ["clock", "time", "three"] },
      { emoji: "⏳", keywords: ["hourglass", "sand", "time", "waiting"] },
    ],
  },
  {
    id: "symbols",
    name: "Symbols",
    icon: "❤️",
    emojis: [
      { emoji: "❤️", keywords: ["red", "heart", "love"] },
      { emoji: "🧡", keywords: ["orange", "heart"] },
      { emoji: "💛", keywords: ["yellow", "heart"] },
      { emoji: "💚", keywords: ["green", "heart"] },
      { emoji: "💙", keywords: ["blue", "heart"] },
      { emoji: "💜", keywords: ["purple", "heart"] },
      { emoji: "🖤", keywords: ["black", "heart"] },
      { emoji: "🤍", keywords: ["white", "heart"] },
      { emoji: "🤎", keywords: ["brown", "heart"] },
      { emoji: "💔", keywords: ["broken", "heart"] },
      { emoji: "❣️", keywords: ["heart", "exclamation"] },
      { emoji: "💕", keywords: ["two", "hearts"] },
      { emoji: "💞", keywords: ["revolving", "hearts"] },
      { emoji: "💓", keywords: ["beating", "heart"] },
      { emoji: "💗", keywords: ["growing", "heart"] },
      { emoji: "💖", keywords: ["sparkling", "heart"] },
      { emoji: "💘", keywords: ["cupid", "heart", "arrow"] },
      { emoji: "💝", keywords: ["ribbon", "heart", "gift"] },
      { emoji: "💯", keywords: ["hundred", "100", "score", "perfect"] },
      { emoji: "💢", keywords: ["anger", "comic"] },
      { emoji: "💬", keywords: ["speech", "bubble", "chat", "message"] },
      { emoji: "💭", keywords: ["thought", "bubble", "think"] },
      { emoji: "🗯️", keywords: ["anger", "bubble"] },
      { emoji: "🔔", keywords: ["bell", "notification", "alert"] },
      { emoji: "🔕", keywords: ["bell", "mute", "silent"] },
      { emoji: "⚠️", keywords: ["warning", "alert", "caution"] },
      { emoji: "⛔", keywords: ["no", "entry", "stop"] },
      { emoji: "🚫", keywords: ["prohibited", "forbidden"] },
      { emoji: "✅", keywords: ["check", "mark", "correct", "verified", "done", "yes"] },
      { emoji: "❌", keywords: ["cross", "mark", "wrong", "no"] },
      { emoji: "❓", keywords: ["question", "mark", "help"] },
      { emoji: "❗", keywords: ["exclamation", "mark", "important"] },
      { emoji: "💤", keywords: ["sleep", "zzz"] },
      { emoji: "🎵", keywords: ["musical", "note", "song"] },
      { emoji: "🎶", keywords: ["musical", "notes", "melody"] },
      { emoji: "🔊", keywords: ["speaker", "loud", "sound", "volume"] },
      { emoji: "🔈", keywords: ["speaker", "soft", "low"] },
      { emoji: "⭐", keywords: ["star", "favorite"] },
      { emoji: "✨", keywords: ["sparkles", "shine", "magic", "clean", "new"] },
      { emoji: "💫", keywords: ["dizzy", "star"] },
      { emoji: "🔥", keywords: ["fire", "flame", "lit", "hot"] },
      { emoji: "⚡", keywords: ["zap", "lightning", "fast", "bolt"] },
      { emoji: "💥", keywords: ["collision", "boom", "explode"] },
      { emoji: "🎯", keywords: ["target", "bullseye", "goal", "accuracy"] },
      { emoji: "🛑", keywords: ["stop", "sign", "halt"] },
      { emoji: "🆗", keywords: ["ok", "button"] },
      { emoji: "🆙", keywords: ["up", "button"] },
      { emoji: "🆒", keywords: ["cool", "button"] },
      { emoji: "🆕", keywords: ["new", "button"] },
      { emoji: "🆓", keywords: ["free", "button"] },
    ],
  },
  {
    id: "celebration",
    name: "Celebration",
    icon: "🎉",
    emojis: [
      { emoji: "🎉", keywords: ["party", "popper", "celebrate", "tada", "congrats"] },
      { emoji: "🎊", keywords: ["confetti", "ball", "celebration"] },
      { emoji: "🎈", keywords: ["balloon", "birthday"] },
      { emoji: "🎁", keywords: ["gift", "present", "box"] },
      { emoji: "🎀", keywords: ["ribbon", "bow"] },
      { emoji: "🪄", keywords: ["magic", "wand", "create"] },
      { emoji: "🏆", keywords: ["trophy", "winner", "first", "champion", "award"] },
      { emoji: "🥇", keywords: ["first", "place", "gold", "medal"] },
      { emoji: "🥈", keywords: ["second", "place", "silver", "medal"] },
      { emoji: "🥉", keywords: ["third", "place", "bronze", "medal"] },
      { emoji: "🏅", keywords: ["sports", "medal", "honor"] },
      { emoji: "🎖️", keywords: ["military", "medal", "distinction"] },
      { emoji: "🚀", keywords: ["rocket", "launch", "ship", "fast"] },
      { emoji: "🌟", keywords: ["glowing", "star", "bright"] },
      { emoji: "👑", keywords: ["crown", "king", "queen", "royal"] },
      { emoji: "🎨", keywords: ["artist", "palette", "art", "design"] },
      { emoji: "🎬", keywords: ["clapper", "board", "cinema", "movie"] },
      { emoji: "🎤", keywords: ["microphone", "sing", "audio", "speech"] },
      { emoji: "🎧", keywords: ["headphone", "audio", "music", "listen"] },
      { emoji: "🎼", keywords: ["musical", "score"] },
      { emoji: "🎹", keywords: ["musical", "keyboard", "piano"] },
      { emoji: "🥁", keywords: ["drum", "percussion"] },
      { emoji: "🎷", keywords: ["saxophone", "jazz"] },
      { emoji: "🎺", keywords: ["trumpet", "brass"] },
      { emoji: "🎸", keywords: ["guitar", "rock"] },
      { emoji: "🎲", keywords: ["game", "die", "dice", "random"] },
      { emoji: "♟️", keywords: ["chess", "pawn", "strategy"] },
      { emoji: "🎳", keywords: ["bowling", "strike"] },
      { emoji: "🎮", keywords: ["video", "game", "controller"] },
      { emoji: "🎪", keywords: ["circus", "tent"] },
      { emoji: "🎭", keywords: ["performing", "arts", "theater", "drama"] },
      { emoji: "🧵", keywords: ["thread", "spool"] },
      { emoji: "🧶", keywords: ["yarn", "ball"] },
      { emoji: "🪅", keywords: ["pinata", "celebrate"] },
      { emoji: "🔮", keywords: ["crystal", "ball"] },
      { emoji: "🥂", keywords: ["clinking", "glasses", "cheers", "toast"] },
      { emoji: "🍻", keywords: ["clinking", "beer", "mugs"] },
      { emoji: "⚽", keywords: ["soccer", "ball", "football"] },
      { emoji: "🏀", keywords: ["basketball", "hoop"] },
      { emoji: "🏈", keywords: ["american", "football"] },
      { emoji: "🎾", keywords: ["tennis", "ball"] },
    ],
  },
  {
    id: "daily",
    name: "Daily",
    icon: "☕",
    emojis: [
      { emoji: "☕", keywords: ["coffee", "tea", "hot", "drink", "morning"] },
      { emoji: "🍵", keywords: ["matcha", "green", "tea"] },
      { emoji: "🧃", keywords: ["beverage", "juice", "box"] },
      { emoji: "🥤", keywords: ["cup", "straw", "soda"] },
      { emoji: "🍎", keywords: ["red", "apple", "fruit", "teacher"] },
      { emoji: "🍊", keywords: ["orange", "tangerine", "citrus"] },
      { emoji: "🍋", keywords: ["lemon", "sour"] },
      { emoji: "🍌", keywords: ["banana", "fruit"] },
      { emoji: "🍉", keywords: ["watermelon", "summer"] },
      { emoji: "🍇", keywords: ["grapes", "fruit"] },
      { emoji: "🍓", keywords: ["strawberry", "berry"] },
      { emoji: "🍒", keywords: ["cherries", "fruit"] },
      { emoji: "🥑", keywords: ["avocado", "healthy"] },
      { emoji: "🥪", keywords: ["sandwich", "lunch"] },
      { emoji: "🥗", keywords: ["green", "salad", "healthy"] },
      { emoji: "🍕", keywords: ["pizza", "slice", "cheese"] },
      { emoji: "🍔", keywords: ["hamburger", "burger"] },
      { emoji: "🌱", keywords: ["seedling", "sprout", "plant", "grow"] },
      { emoji: "🌿", keywords: ["herb", "leaves"] },
      { emoji: "☘️", keywords: ["shamrock", "clover"] },
      { emoji: "🍀", keywords: ["four", "leaf", "clover", "lucky"] },
      { emoji: "🍃", keywords: ["leaf", "fluttering", "wind"] },
      { emoji: "🍂", keywords: ["fallen", "leaf", "autumn"] },
      { emoji: "🍁", keywords: ["maple", "leaf", "fall", "canada"] },
      { emoji: "🍄", keywords: ["mushroom", "fungus"] },
      { emoji: "💐", keywords: ["bouquet", "flowers"] },
      { emoji: "🌷", keywords: ["tulip", "flower"] },
      { emoji: "🌹", keywords: ["rose", "flower", "red"] },
      { emoji: "🌻", keywords: ["sunflower", "summer"] },
      { emoji: "🌞", keywords: ["sun", "face", "warm", "day"] },
      { emoji: "🌙", keywords: ["crescent", "moon", "night"] },
      { emoji: "🌎", keywords: ["globe", "americas", "world", "earth"] },
      { emoji: "🌍", keywords: ["globe", "africa", "europe", "world"] },
      { emoji: "🌏", keywords: ["globe", "asia", "australia", "world"] },
      { emoji: "🪐", keywords: ["ringed", "planet", "saturn", "space"] },
      { emoji: "🚲", keywords: ["bicycle", "bike"] },
      { emoji: "🚗", keywords: ["automobile", "car"] },
      { emoji: "✈️", keywords: ["airplane", "travel", "flight"] },
      { emoji: "🏖️", keywords: ["beach", "umbrella", "vacation"] },
      { emoji: "🏔️", keywords: ["snow", "capped", "mountain"] },
    ],
  },
  {
    id: "flags",
    name: "Flags",
    icon: "🌐",
    emojis: [
      // Global & Special
      { emoji: "🇺🇳", keywords: ["un", "united", "nations", "international", "global", "flag"] },
      { emoji: "🇪🇺", keywords: ["eu", "european", "union", "europe", "flag"] },
      { emoji: "🏳️‍🌈", keywords: ["rainbow", "pride", "lgbtq", "flag"] },
      { emoji: "🏳️‍⚧️", keywords: ["transgender", "pride", "flag"] },
      { emoji: "🏁", keywords: ["chequered", "finish", "race", "flag"] },
      { emoji: "🚩", keywords: ["triangular", "red", "flag"] },
      { emoji: "🎌", keywords: ["crossed", "japanese", "flags"] },
      { emoji: "🏴", keywords: ["black", "flag"] },
      { emoji: "🏳️", keywords: ["white", "flag", "peace"] },

      // Americas
      { emoji: "🇺🇸", keywords: ["united", "states", "usa", "america", "us", "flag"] },
      { emoji: "🇨🇦", keywords: ["canada", "canadian", "ca", "flag"] },
      { emoji: "🇲🇽", keywords: ["mexico", "mexican", "mx", "flag"] },
      { emoji: "🇧🇷", keywords: ["brazil", "brasil", "br", "flag"] },
      { emoji: "🇦🇷", keywords: ["argentina", "ar", "flag"] },
      { emoji: "🇨🇴", keywords: ["colombia", "co", "flag"] },
      { emoji: "🇨🇱", keywords: ["chile", "cl", "flag"] },
      { emoji: "🇵🇪", keywords: ["peru", "pe", "flag"] },
      { emoji: "🇻🇪", keywords: ["venezuela", "ve", "flag"] },
      { emoji: "🇪🇨", keywords: ["ecuador", "ec", "flag"] },
      { emoji: "🇧🇴", keywords: ["bolivia", "bo", "flag"] },
      { emoji: "🇵🇾", keywords: ["paraguay", "py", "flag"] },
      { emoji: "🇺🇾", keywords: ["uruguay", "uy", "flag"] },
      { emoji: "🇵🇦", keywords: ["panama", "pa", "flag"] },
      { emoji: "🇨🇷", keywords: ["costa", "rica", "cr", "flag"] },
      { emoji: "🇬🇹", keywords: ["guatemala", "gt", "flag"] },
      { emoji: "🇸🇻", keywords: ["el", "salvador", "sv", "flag"] },
      { emoji: "🇭🇳", keywords: ["honduras", "hn", "flag"] },
      { emoji: "🇳🇮", keywords: ["nicaragua", "ni", "flag"] },
      { emoji: "🇨🇺", keywords: ["cuba", "cu", "flag"] },
      { emoji: "🇭🇹", keywords: ["haiti", "ht", "flag"] },
      { emoji: "🇩🇴", keywords: ["dominican", "republic", "do", "flag"] },
      { emoji: "🇯🇲", keywords: ["jamaica", "jm", "flag"] },
      { emoji: "🇧🇸", keywords: ["bahamas", "bs", "flag"] },
      { emoji: "🇧🇧", keywords: ["barbados", "bb", "flag"] },
      { emoji: "🇹🇹", keywords: ["trinidad", "tobago", "tt", "flag"] },
      { emoji: "🇵🇷", keywords: ["puerto", "rico", "pr", "flag"] },

      // Europe
      { emoji: "🇬🇧", keywords: ["united", "kingdom", "uk", "great", "britain", "england", "flag"] },
      { emoji: "🇫🇷", keywords: ["france", "french", "fr", "flag"] },
      { emoji: "🇩🇪", keywords: ["germany", "german", "de", "flag"] },
      { emoji: "🇮🇹", keywords: ["italy", "italian", "it", "flag"] },
      { emoji: "🇪🇸", keywords: ["spain", "spanish", "es", "flag"] },
      { emoji: "🇵🇹", keywords: ["portugal", "portuguese", "pt", "flag"] },
      { emoji: "🇳🇱", keywords: ["netherlands", "dutch", "holland", "nl", "flag"] },
      { emoji: "🇧🇪", keywords: ["belgium", "belgian", "be", "flag"] },
      { emoji: "🇨🇭", keywords: ["switzerland", "swiss", "ch", "flag"] },
      { emoji: "🇦🇹", keywords: ["austria", "at", "flag"] },
      { emoji: "🇸🇪", keywords: ["sweden", "swedish", "se", "flag"] },
      { emoji: "🇳🇴", keywords: ["norway", "norwegian", "no", "flag"] },
      { emoji: "🇩🇰", keywords: ["denmark", "danish", "dk", "flag"] },
      { emoji: "🇫🇮", keywords: ["finland", "finnish", "fi", "flag"] },
      { emoji: "🇮🇪", keywords: ["ireland", "irish", "ie", "flag"] },
      { emoji: "🇵🇱", keywords: ["poland", "polish", "pl", "flag"] },
      { emoji: "🇺🇦", keywords: ["ukraine", "ua", "flag"] },
      { emoji: "🇬🇷", keywords: ["greece", "greek", "gr", "flag"] },
      { emoji: "🇷🇴", keywords: ["romania", "ro", "flag"] },
      { emoji: "🇨🇿", keywords: ["czech", "republic", "cz", "flag"] },
      { emoji: "🇭🇺", keywords: ["hungary", "hu", "flag"] },
      { emoji: "🇮🇸", keywords: ["iceland", "is", "flag"] },
      { emoji: "🇭🇷", keywords: ["croatia", "hr", "flag"] },
      { emoji: "🇷🇸", keywords: ["serbia", "rs", "flag"] },
      { emoji: "🇧🇬", keywords: ["bulgaria", "bg", "flag"] },
      { emoji: "🇸🇰", keywords: ["slovakia", "sk", "flag"] },
      { emoji: "🇱🇹", keywords: ["lithuania", "lt", "flag"] },
      { emoji: "🇱🇻", keywords: ["latvia", "lv", "flag"] },
      { emoji: "🇪🇪", keywords: ["estonia", "ee", "flag"] },
      { emoji: "🇻🇦", keywords: ["vatican", "city", "holy", "see", "flag"] },
      { emoji: "🇲🇨", keywords: ["monaco", "mc", "flag"] },
      { emoji: "🇹🇷", keywords: ["turkey", "turkiye", "tr", "flag"] },

      // Africa
      { emoji: "🇨🇩", keywords: ["congo", "drc", "democratic", "republic", "cd", "flag"] },
      { emoji: "🇨🇬", keywords: ["congo", "brazzaville", "cg", "flag"] },
      { emoji: "🇿🇦", keywords: ["south", "africa", "za", "flag"] },
      { emoji: "🇳🇬", keywords: ["nigeria", "nigerian", "ng", "flag"] },
      { emoji: "🇪🇬", keywords: ["egypt", "eg", "flag"] },
      { emoji: "🇰🇪", keywords: ["kenya", "ke", "flag"] },
      { emoji: "🇬🇭", keywords: ["ghana", "gh", "flag"] },
      { emoji: "🇪🇹", keywords: ["ethiopia", "et", "flag"] },
      { emoji: "🇲🇦", keywords: ["morocco", "ma", "flag"] },
      { emoji: "🇩🇿", keywords: ["algeria", "dz", "flag"] },
      { emoji: "🇹🇳", keywords: ["tunisia", "tn", "flag"] },
      { emoji: "🇨🇲", keywords: ["cameroon", "cm", "flag"] },
      { emoji: "🇸🇳", keywords: ["senegal", "sn", "flag"] },
      { emoji: "🇨🇮", keywords: ["ivory", "coast", "cote", "divoire", "ci", "flag"] },
      { emoji: "🇷🇼", keywords: ["rwanda", "rw", "flag"] },
      { emoji: "🇺🇬", keywords: ["uganda", "ug", "flag"] },
      { emoji: "🇹🇿", keywords: ["tanzania", "tz", "flag"] },
      { emoji: "🇦🇴", keywords: ["angola", "ao", "flag"] },
      { emoji: "🇲🇿", keywords: ["mozambique", "mz", "flag"] },
      { emoji: "🇿🇼", keywords: ["zimbabwe", "zw", "flag"] },
      { emoji: "🇿🇲", keywords: ["zambia", "zm", "flag"] },
      { emoji: "🇧🇼", keywords: ["botswana", "bw", "flag"] },
      { emoji: "🇳🇦", keywords: ["namibia", "na", "flag"] },
      { emoji: "🇲🇬", keywords: ["madagascar", "mg", "flag"] },
      { emoji: "🇸🇩", keywords: ["sudan", "sd", "flag"] },
      { emoji: "🇸🇴", keywords: ["somalia", "so", "flag"] },
      { emoji: "🇲🇱", keywords: ["mali", "ml", "flag"] },
      { emoji: "🇳🇪", keywords: ["niger", "ne", "flag"] },
      { emoji: "🇧🇫", keywords: ["burkina", "faso", "bf", "flag"] },
      { emoji: "🇬🇳", keywords: ["guinea", "gn", "flag"] },
      { emoji: "🇱🇷", keywords: ["liberia", "lr", "flag"] },
      { emoji: "🇸🇱", keywords: ["sierra", "leone", "sl", "flag"] },

      // Asia & Middle East
      { emoji: "🇨🇳", keywords: ["china", "chinese", "cn", "flag"] },
      { emoji: "🇯🇵", keywords: ["japan", "japanese", "jp", "flag"] },
      { emoji: "🇰🇷", keywords: ["south", "korea", "korean", "kr", "flag"] },
      { emoji: "🇮🇳", keywords: ["india", "indian", "in", "flag"] },
      { emoji: "🇮🇩", keywords: ["indonesia", "id", "flag"] },
      { emoji: "🇵🇰", keywords: ["pakistan", "pk", "flag"] },
      { emoji: "🇧🇩", keywords: ["bangladesh", "bd", "flag"] },
      { emoji: "🇵🇭", keywords: ["philippines", "filipino", "ph", "flag"] },
      { emoji: "🇻🇳", keywords: ["vietnam", "vietnamese", "vn", "flag"] },
      { emoji: "🇹🇭", keywords: ["thailand", "thai", "th", "flag"] },
      { emoji: "🇲🇾", keywords: ["malaysia", "my", "flag"] },
      { emoji: "🇸🇬", keywords: ["singapore", "sg", "flag"] },
      { emoji: "🇸🇦", keywords: ["saudi", "arabia", "sa", "flag"] },
      { emoji: "🇦🇪", keywords: ["united", "arab", "emirates", "uae", "dubai", "ae", "flag"] },
      { emoji: "🇮🇱", keywords: ["israel", "il", "flag"] },
      { emoji: "🇵🇸", keywords: ["palestine", "ps", "flag"] },
      { emoji: "🇮🇷", keywords: ["iran", "ir", "flag"] },
      { emoji: "🇮🇶", keywords: ["iraq", "iq", "flag"] },
      { emoji: "🇶🇦", keywords: ["qatar", "qa", "flag"] },
      { emoji: "🇰🇼", keywords: ["kuwait", "kw", "flag"] },
      { emoji: "🇴🇲", keywords: ["oman", "om", "flag"] },
      { emoji: "🇯🇴", keywords: ["jordan", "jo", "flag"] },
      { emoji: "🇱🇧", keywords: ["lebanon", "lb", "flag"] },
      { emoji: "🇸🇾", keywords: ["syria", "sy", "flag"] },
      { emoji: "🇾🇪", keywords: ["yemen", "ye", "flag"] },
      { emoji: "🇰🇿", keywords: ["kazakhstan", "kz", "flag"] },
      { emoji: "🇺🇿", keywords: ["uzbekistan", "uz", "flag"] },
      { emoji: "🇳🇵", keywords: ["nepal", "np", "flag"] },
      { emoji: "🇱🇰", keywords: ["sri", "lanka", "lk", "flag"] },
      { emoji: "🇲🇲", keywords: ["myanmar", "burma", "mm", "flag"] },
      { emoji: "🇰🇭", keywords: ["cambodia", "kh", "flag"] },
      { emoji: "🇹🇼", keywords: ["taiwan", "tw", "flag"] },
      { emoji: "🇭🇰", keywords: ["hong", "kong", "hk", "flag"] },

      // Oceania
      { emoji: "🇦🇺", keywords: ["australia", "aussie", "au", "flag"] },
      { emoji: "🇳🇿", keywords: ["new", "zealand", "kiwi", "nz", "flag"] },
      { emoji: "🇫🇯", keywords: ["fiji", "fj", "flag"] },
      { emoji: "🇵🇬", keywords: ["papua", "new", "guinea", "pg", "flag"] },
      { emoji: "🇼🇸", keywords: ["samoa", "ws", "flag"] },
      { emoji: "🇹🇴", keywords: ["tonga", "to", "flag"] },
      { emoji: "🇻🇺", keywords: ["vanuatu", "vu", "flag"] },
      { emoji: "🇸🇧", keywords: ["solomon", "islands", "sb", "flag"] },
    ],
  },
]

export function searchEmojis(query: string): string[] {
  const q = query.trim().toLowerCase()
  if (!q) return []
  const matches: string[] = []
  for (const category of EMOJI_CATALOG) {
    for (const item of category.emojis) {
      if (item.keywords.some((k) => k.includes(q))) {
        matches.push(item.emoji)
      }
    }
  }
  return Array.from(new Set(matches))
}
